name: ubuntu2004-ansible-latest
on:
  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    paths:
      - 'ubuntu2004-ansible-latest/**'
  pull_request:
    paths:
      - 'ubuntu2004-ansible-latest/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerimage:
          - ubuntu2004-ansible
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.dockerimage }}-latest
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-${{ matrix.dockerimage }}:test
          platform: linux/amd64,linux/arm64
      -
        name: Test
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/docker-${{ matrix.dockerimage }}:test
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.dockerimage }}-latest
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-${{ matrix.dockerimage }}:latest
          platform: linux/amd64,linux/arm64
        if: github.ref == 'refs/heads/master'
